"""marketplace: catalog, requests, quotes, orders, reviews, messaging

Revision ID: 5bded70e1a7e
Revises: 44c91a7d6175
Create Date: 2026-09-24 12:59:05.045020
"""
from collections.abc import Sequence

import sqlalchemy as sa
from alembic import op


revision: str = '5bded70e1a7e'
down_revision: str | None = '44c91a7d6175'
branch_labels: str | Sequence[str] | None = None
depends_on: str | Sequence[str] | None = None

# Initial service catalog (frozen here; admins manage it from the panel afterwards).
CATEGORIES = [
    (1, "alteration", "تعديل", "Alteration", 1),
    (2, "repair", "تصليح", "Repair", 2),
    (3, "custom", "تفصيل", "Custom tailoring", 3),
]
SERVICES = [
    (1, "hem_pants", "تقصير بنطلون", "Pants hemming"),
    (1, "take_in", "تضييق", "Take in"),
    (1, "let_out", "توسيع", "Let out"),
    (1, "shorten_sleeves", "تقصير أكمام", "Sleeve shortening"),
    (1, "thobe_alteration", "تعديل ثوب", "Thobe alteration"),
    (1, "dress_alteration", "تعديل فستان", "Dress alteration"),
    (1, "abaya_alteration", "تعديل عباية", "Abaya alteration"),
    (2, "zipper_replacement", "تغيير سحّاب", "Zipper replacement"),
    (2, "buttons", "تركيب أزرار", "Buttons"),
    (2, "tear_repair", "تصليح شق", "Tear repair"),
    (2, "lining_replacement", "تغيير بطانة", "Lining replacement"),
    (3, "custom_thobe", "تفصيل ثوب", "Custom thobe"),
    (3, "custom_suit", "تفصيل بدلة", "Custom suit"),
    (3, "custom_abaya", "تفصيل عباية", "Custom abaya"),
    (3, "evening_dress", "فستان سهرة", "Evening dress"),
    (3, "wedding_dress", "فستان زفاف", "Wedding dress"),
    (3, "kids_clothing", "ملابس أطفال", "Kids' clothing"),
    (3, "uniforms", "زي موحد", "Uniforms"),
]


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('service_categories',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('slug', sa.String(length=60), nullable=False),
    sa.Column('name_ar', sa.String(length=80), nullable=False),
    sa.Column('name_en', sa.String(length=80), nullable=False),
    sa.Column('sort_order', sa.Integer(), nullable=False),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_service_categories')),
    sa.UniqueConstraint('slug', name=op.f('uq_service_categories_slug'))
    )
    op.create_table('audit_logs',
    sa.Column('actor_id', sa.Uuid(), nullable=True),
    sa.Column('action', sa.String(length=60), nullable=False),
    sa.Column('target_type', sa.String(length=40), nullable=False),
    sa.Column('target_id', sa.String(length=64), nullable=False),
    sa.Column('details', sa.Text(), nullable=True),
    sa.Column('id', sa.Uuid(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('(CURRENT_TIMESTAMP)'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('(CURRENT_TIMESTAMP)'), nullable=False),
    sa.ForeignKeyConstraint(['actor_id'], ['users.id'], name=op.f('fk_audit_logs_actor_id_users'), ondelete='SET NULL'),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_audit_logs'))
    )
    with op.batch_alter_table('audit_logs', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_audit_logs_actor_id'), ['actor_id'], unique=False)

    op.create_table('notifications',
    sa.Column('user_id', sa.Uuid(), nullable=False),
    sa.Column('type', sa.String(length=40), nullable=False),
    sa.Column('data', sa.JSON(), nullable=False),
    sa.Column('link', sa.String(length=200), nullable=True),
    sa.Column('read_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('id', sa.Uuid(), nullable=False),
    sa.ForeignKeyConstraint(['user_id'], ['users.id'], name=op.f('fk_notifications_user_id_users'), ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_notifications'))
    )
    with op.batch_alter_table('notifications', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_notifications_created_at'), ['created_at'], unique=False)
        batch_op.create_index(batch_op.f('ix_notifications_user_id'), ['user_id'], unique=False)

    op.create_table('services',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('category_id', sa.Integer(), nullable=False),
    sa.Column('slug', sa.String(length=60), nullable=False),
    sa.Column('name_ar', sa.String(length=80), nullable=False),
    sa.Column('name_en', sa.String(length=80), nullable=False),
    sa.Column('is_active', sa.Boolean(), nullable=False),
    sa.Column('sort_order', sa.Integer(), nullable=False),
    sa.ForeignKeyConstraint(['category_id'], ['service_categories.id'], name=op.f('fk_services_category_id_service_categories'), ondelete='RESTRICT'),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_services')),
    sa.UniqueConstraint('slug', name=op.f('uq_services_slug'))
    )
    with op.batch_alter_table('services', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_services_category_id'), ['category_id'], unique=False)

    op.create_table('job_requests',
    sa.Column('customer_id', sa.Uuid(), nullable=False),
    sa.Column('service_id', sa.Integer(), nullable=True),
    sa.Column('title', sa.String(length=120), nullable=False),
    sa.Column('description', sa.Text(), nullable=False),
    sa.Column('city', sa.String(length=40), nullable=False),
    sa.Column('address_id', sa.Uuid(), nullable=True),
    sa.Column('preferred_date', sa.Date(), nullable=True),
    sa.Column('budget_max', sa.Numeric(precision=10, scale=2), nullable=True),
    sa.Column('needs_pickup', sa.Boolean(), nullable=False),
    sa.Column('needs_delivery', sa.Boolean(), nullable=False),
    sa.Column('photo_urls', sa.JSON(), nullable=False),
    sa.Column('status', sa.Enum('draft', 'open', 'quotes_received', 'tailor_selected', 'in_progress', 'completed', 'cancelled', 'expired', name='requeststatus', native_enum=False, length=32), nullable=False),
    sa.Column('id', sa.Uuid(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('(CURRENT_TIMESTAMP)'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('(CURRENT_TIMESTAMP)'), nullable=False),
    sa.ForeignKeyConstraint(['address_id'], ['addresses.id'], name=op.f('fk_job_requests_address_id_addresses'), ondelete='SET NULL'),
    sa.ForeignKeyConstraint(['customer_id'], ['users.id'], name=op.f('fk_job_requests_customer_id_users'), ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['service_id'], ['services.id'], name=op.f('fk_job_requests_service_id_services'), ondelete='SET NULL'),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_job_requests'))
    )
    with op.batch_alter_table('job_requests', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_job_requests_city'), ['city'], unique=False)
        batch_op.create_index(batch_op.f('ix_job_requests_customer_id'), ['customer_id'], unique=False)
        batch_op.create_index(batch_op.f('ix_job_requests_status'), ['status'], unique=False)

    op.create_table('portfolio_items',
    sa.Column('tailor_id', sa.Uuid(), nullable=False),
    sa.Column('image_url', sa.String(length=500), nullable=False),
    sa.Column('title', sa.String(length=120), nullable=False),
    sa.Column('description', sa.Text(), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('(CURRENT_TIMESTAMP)'), nullable=False),
    sa.Column('id', sa.Uuid(), nullable=False),
    sa.ForeignKeyConstraint(['tailor_id'], ['tailor_profiles.user_id'], name=op.f('fk_portfolio_items_tailor_id_tailor_profiles'), ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_portfolio_items'))
    )
    with op.batch_alter_table('portfolio_items', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_portfolio_items_tailor_id'), ['tailor_id'], unique=False)

    op.create_table('tailor_services',
    sa.Column('tailor_id', sa.Uuid(), nullable=False),
    sa.Column('service_id', sa.Integer(), nullable=False),
    sa.Column('price_from', sa.Numeric(precision=10, scale=2), nullable=False),
    sa.Column('duration_days', sa.Integer(), nullable=True),
    sa.ForeignKeyConstraint(['service_id'], ['services.id'], name=op.f('fk_tailor_services_service_id_services'), ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['tailor_id'], ['tailor_profiles.user_id'], name=op.f('fk_tailor_services_tailor_id_tailor_profiles'), ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('tailor_id', 'service_id', name=op.f('pk_tailor_services'))
    )
    with op.batch_alter_table('tailor_services', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_tailor_services_service_id'), ['service_id'], unique=False)

    op.create_table('conversations',
    sa.Column('customer_id', sa.Uuid(), nullable=False),
    sa.Column('tailor_id', sa.Uuid(), nullable=False),
    sa.Column('request_id', sa.Uuid(), nullable=True),
    sa.Column('last_message_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('customer_last_read_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('tailor_last_read_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('id', sa.Uuid(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('(CURRENT_TIMESTAMP)'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('(CURRENT_TIMESTAMP)'), nullable=False),
    sa.ForeignKeyConstraint(['customer_id'], ['users.id'], name=op.f('fk_conversations_customer_id_users'), ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['request_id'], ['job_requests.id'], name=op.f('fk_conversations_request_id_job_requests'), ondelete='SET NULL'),
    sa.ForeignKeyConstraint(['tailor_id'], ['users.id'], name=op.f('fk_conversations_tailor_id_users'), ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_conversations'))
    )
    with op.batch_alter_table('conversations', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_conversations_customer_id'), ['customer_id'], unique=False)
        batch_op.create_index(batch_op.f('ix_conversations_request_id'), ['request_id'], unique=False)
        batch_op.create_index(batch_op.f('ix_conversations_tailor_id'), ['tailor_id'], unique=False)

    op.create_table('quotes',
    sa.Column('request_id', sa.Uuid(), nullable=False),
    sa.Column('tailor_id', sa.Uuid(), nullable=False),
    sa.Column('price', sa.Numeric(precision=10, scale=2), nullable=False),
    sa.Column('duration_days', sa.Integer(), nullable=False),
    sa.Column('offers_pickup', sa.Boolean(), nullable=False),
    sa.Column('offers_delivery', sa.Boolean(), nullable=False),
    sa.Column('message', sa.Text(), nullable=True),
    sa.Column('status', sa.Enum('pending', 'accepted', 'rejected', 'expired', 'withdrawn', name='quotestatus', native_enum=False, length=32), nullable=False),
    sa.Column('id', sa.Uuid(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('(CURRENT_TIMESTAMP)'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('(CURRENT_TIMESTAMP)'), nullable=False),
    sa.CheckConstraint('duration_days > 0', name=op.f('ck_quotes_duration_positive')),
    sa.CheckConstraint('price > 0', name=op.f('ck_quotes_price_positive')),
    sa.ForeignKeyConstraint(['request_id'], ['job_requests.id'], name=op.f('fk_quotes_request_id_job_requests'), ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['tailor_id'], ['users.id'], name=op.f('fk_quotes_tailor_id_users'), ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_quotes')),
    sa.UniqueConstraint('request_id', 'tailor_id', name=op.f('uq_quotes_request_id'))
    )
    with op.batch_alter_table('quotes', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_quotes_request_id'), ['request_id'], unique=False)
        batch_op.create_index(batch_op.f('ix_quotes_tailor_id'), ['tailor_id'], unique=False)

    op.create_table('messages',
    sa.Column('conversation_id', sa.Uuid(), nullable=False),
    sa.Column('sender_id', sa.Uuid(), nullable=False),
    sa.Column('body', sa.Text(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('id', sa.Uuid(), nullable=False),
    sa.ForeignKeyConstraint(['conversation_id'], ['conversations.id'], name=op.f('fk_messages_conversation_id_conversations'), ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['sender_id'], ['users.id'], name=op.f('fk_messages_sender_id_users'), ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_messages'))
    )
    with op.batch_alter_table('messages', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_messages_conversation_id'), ['conversation_id'], unique=False)
        batch_op.create_index(batch_op.f('ix_messages_created_at'), ['created_at'], unique=False)

    op.create_table('orders',
    sa.Column('reference', sa.String(length=16), nullable=False),
    sa.Column('request_id', sa.Uuid(), nullable=False),
    sa.Column('quote_id', sa.Uuid(), nullable=False),
    sa.Column('customer_id', sa.Uuid(), nullable=False),
    sa.Column('tailor_id', sa.Uuid(), nullable=False),
    sa.Column('title', sa.String(length=120), nullable=False),
    sa.Column('price', sa.Numeric(precision=10, scale=2), nullable=False),
    sa.Column('commission_rate', sa.Numeric(precision=5, scale=4), nullable=False),
    sa.Column('commission_amount', sa.Numeric(precision=10, scale=2), nullable=False),
    sa.Column('tailor_payout', sa.Numeric(precision=10, scale=2), nullable=False),
    sa.Column('payment_method', sa.String(length=20), nullable=False),
    sa.Column('pickup', sa.Boolean(), nullable=False),
    sa.Column('delivery', sa.Boolean(), nullable=False),
    sa.Column('due_date', sa.Date(), nullable=False),
    sa.Column('status', sa.Enum('pending_payment', 'confirmed', 'pickup_scheduled', 'picked_up', 'at_tailor', 'in_progress', 'ready', 'out_for_delivery', 'delivered', 'completed', 'cancelled', 'disputed', name='orderstatus', native_enum=False, length=32), nullable=False),
    sa.Column('completed_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('id', sa.Uuid(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('(CURRENT_TIMESTAMP)'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('(CURRENT_TIMESTAMP)'), nullable=False),
    sa.ForeignKeyConstraint(['customer_id'], ['users.id'], name=op.f('fk_orders_customer_id_users'), ondelete='RESTRICT'),
    sa.ForeignKeyConstraint(['quote_id'], ['quotes.id'], name=op.f('fk_orders_quote_id_quotes'), ondelete='RESTRICT'),
    sa.ForeignKeyConstraint(['request_id'], ['job_requests.id'], name=op.f('fk_orders_request_id_job_requests'), ondelete='RESTRICT'),
    sa.ForeignKeyConstraint(['tailor_id'], ['users.id'], name=op.f('fk_orders_tailor_id_users'), ondelete='RESTRICT'),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_orders')),
    sa.UniqueConstraint('quote_id', name=op.f('uq_orders_quote_id')),
    sa.UniqueConstraint('reference', name=op.f('uq_orders_reference')),
    sa.UniqueConstraint('request_id', name=op.f('uq_orders_request_id'))
    )
    with op.batch_alter_table('orders', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_orders_customer_id'), ['customer_id'], unique=False)
        batch_op.create_index(batch_op.f('ix_orders_status'), ['status'], unique=False)
        batch_op.create_index(batch_op.f('ix_orders_tailor_id'), ['tailor_id'], unique=False)

    op.create_table('order_events',
    sa.Column('order_id', sa.Uuid(), nullable=False),
    sa.Column('status', sa.Enum('pending_payment', 'confirmed', 'pickup_scheduled', 'picked_up', 'at_tailor', 'in_progress', 'ready', 'out_for_delivery', 'delivered', 'completed', 'cancelled', 'disputed', name='orderstatus', native_enum=False, length=32), nullable=False),
    sa.Column('actor_id', sa.Uuid(), nullable=True),
    sa.Column('note', sa.String(length=500), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('id', sa.Uuid(), nullable=False),
    sa.ForeignKeyConstraint(['actor_id'], ['users.id'], name=op.f('fk_order_events_actor_id_users'), ondelete='SET NULL'),
    sa.ForeignKeyConstraint(['order_id'], ['orders.id'], name=op.f('fk_order_events_order_id_orders'), ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_order_events'))
    )
    with op.batch_alter_table('order_events', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_order_events_order_id'), ['order_id'], unique=False)

    op.create_table('reviews',
    sa.Column('order_id', sa.Uuid(), nullable=False),
    sa.Column('author_id', sa.Uuid(), nullable=False),
    sa.Column('target_user_id', sa.Uuid(), nullable=False),
    sa.Column('rating', sa.Integer(), nullable=False),
    sa.Column('comment', sa.Text(), nullable=True),
    sa.Column('is_hidden', sa.Boolean(), nullable=False),
    sa.Column('id', sa.Uuid(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('(CURRENT_TIMESTAMP)'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('(CURRENT_TIMESTAMP)'), nullable=False),
    sa.CheckConstraint('rating BETWEEN 1 AND 5', name=op.f('ck_reviews_rating_range')),
    sa.ForeignKeyConstraint(['author_id'], ['users.id'], name=op.f('fk_reviews_author_id_users'), ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['order_id'], ['orders.id'], name=op.f('fk_reviews_order_id_orders'), ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['target_user_id'], ['users.id'], name=op.f('fk_reviews_target_user_id_users'), ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_reviews')),
    sa.UniqueConstraint('order_id', 'author_id', name=op.f('uq_reviews_order_id'))
    )
    with op.batch_alter_table('reviews', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_reviews_order_id'), ['order_id'], unique=False)
        batch_op.create_index(batch_op.f('ix_reviews_target_user_id'), ['target_user_id'], unique=False)

    # ### end Alembic commands ###

    categories = sa.table(
        "service_categories", sa.column("id", sa.Integer), sa.column("slug", sa.String),
        sa.column("name_ar", sa.String), sa.column("name_en", sa.String),
        sa.column("sort_order", sa.Integer),
    )
    op.bulk_insert(categories, [
        {"id": i, "slug": slug, "name_ar": ar, "name_en": en, "sort_order": order}
        for i, slug, ar, en, order in CATEGORIES
    ])
    services = sa.table(
        "services", sa.column("category_id", sa.Integer), sa.column("slug", sa.String),
        sa.column("name_ar", sa.String), sa.column("name_en", sa.String),
        sa.column("is_active", sa.Boolean), sa.column("sort_order", sa.Integer),
    )
    op.bulk_insert(services, [
        {"category_id": cat, "slug": slug, "name_ar": ar, "name_en": en, "is_active": True,
         "sort_order": n}
        for n, (cat, slug, ar, en) in enumerate(SERVICES)
    ])
    if op.get_bind().dialect.name == "postgresql":
        # Explicit ids above don't advance the sequence.
        op.execute("SELECT setval('service_categories_id_seq', "
                   "(SELECT MAX(id) FROM service_categories))")


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('reviews', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_reviews_target_user_id'))
        batch_op.drop_index(batch_op.f('ix_reviews_order_id'))

    op.drop_table('reviews')
    with op.batch_alter_table('order_events', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_order_events_order_id'))

    op.drop_table('order_events')
    with op.batch_alter_table('orders', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_orders_tailor_id'))
        batch_op.drop_index(batch_op.f('ix_orders_status'))
        batch_op.drop_index(batch_op.f('ix_orders_customer_id'))

    op.drop_table('orders')
    with op.batch_alter_table('messages', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_messages_created_at'))
        batch_op.drop_index(batch_op.f('ix_messages_conversation_id'))

    op.drop_table('messages')
    with op.batch_alter_table('quotes', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_quotes_tailor_id'))
        batch_op.drop_index(batch_op.f('ix_quotes_request_id'))

    op.drop_table('quotes')
    with op.batch_alter_table('conversations', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_conversations_tailor_id'))
        batch_op.drop_index(batch_op.f('ix_conversations_request_id'))
        batch_op.drop_index(batch_op.f('ix_conversations_customer_id'))

    op.drop_table('conversations')
    with op.batch_alter_table('tailor_services', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_tailor_services_service_id'))

    op.drop_table('tailor_services')
    with op.batch_alter_table('portfolio_items', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_portfolio_items_tailor_id'))

    op.drop_table('portfolio_items')
    with op.batch_alter_table('job_requests', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_job_requests_status'))
        batch_op.drop_index(batch_op.f('ix_job_requests_customer_id'))
        batch_op.drop_index(batch_op.f('ix_job_requests_city'))

    op.drop_table('job_requests')
    with op.batch_alter_table('services', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_services_category_id'))

    op.drop_table('services')
    with op.batch_alter_table('notifications', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_notifications_user_id'))
        batch_op.drop_index(batch_op.f('ix_notifications_created_at'))

    op.drop_table('notifications')
    with op.batch_alter_table('audit_logs', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_audit_logs_actor_id'))

    op.drop_table('audit_logs')
    op.drop_table('service_categories')
    # ### end Alembic commands ###
