"""bookings, booking events, support messages

Revision ID: e1929fa3a01c
Revises: 5bded70e1a7e
Create Date: 2026-10-07 10:13:37.381627
"""
from collections.abc import Sequence

import sqlalchemy as sa
from alembic import op


revision: str = 'e1929fa3a01c'
down_revision: str | None = '5bded70e1a7e'
branch_labels: str | Sequence[str] | None = None
depends_on: str | Sequence[str] | None = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('bookings',
    sa.Column('reference', sa.String(length=16), nullable=False),
    sa.Column('customer_id', sa.Uuid(), nullable=False),
    sa.Column('service_type', sa.Enum('shop_visit', 'van_pickup', 'home_service', 'quick_fix', name='bookingservicetype', native_enum=False, length=32), nullable=False),
    sa.Column('status', sa.String(length=32), nullable=False),
    sa.Column('description', sa.Text(), nullable=False),
    sa.Column('garment', sa.String(length=40), nullable=True),
    sa.Column('quick_items', sa.JSON(), nullable=False),
    sa.Column('photo_urls', sa.JSON(), nullable=False),
    sa.Column('city', sa.String(length=40), nullable=False),
    sa.Column('district', sa.String(length=80), nullable=True),
    sa.Column('address_line', sa.String(length=200), nullable=True),
    sa.Column('contact_phone', sa.String(length=20), nullable=True),
    sa.Column('scheduled_date', sa.Date(), nullable=False),
    sa.Column('slot', sa.String(length=5), nullable=False),
    sa.Column('visit_fee_usd', sa.Numeric(precision=8, scale=2), nullable=False),
    sa.Column('estimate_min_usd', sa.Numeric(precision=8, scale=2), nullable=True),
    sa.Column('estimate_max_usd', sa.Numeric(precision=8, scale=2), nullable=True),
    sa.Column('final_price_usd', sa.Numeric(precision=8, scale=2), nullable=True),
    sa.Column('payment_status', sa.Enum('unpaid', 'paid', name='paymentstatus', native_enum=False, length=32), nullable=False),
    sa.Column('paid_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('assignee_name', sa.String(length=80), nullable=True),
    sa.Column('recommended', sa.Boolean(), nullable=False),
    sa.Column('rating', sa.Integer(), nullable=True),
    sa.Column('review_comment', sa.Text(), nullable=True),
    sa.Column('reviewed_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('cancel_reason', sa.String(length=300), nullable=True),
    sa.Column('completed_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('id', sa.Uuid(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('(CURRENT_TIMESTAMP)'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('(CURRENT_TIMESTAMP)'), nullable=False),
    sa.ForeignKeyConstraint(['customer_id'], ['users.id'], name=op.f('fk_bookings_customer_id_users'), ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_bookings')),
    sa.UniqueConstraint('reference', name=op.f('uq_bookings_reference'))
    )
    with op.batch_alter_table('bookings', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_bookings_customer_id'), ['customer_id'], unique=False)
        batch_op.create_index(batch_op.f('ix_bookings_scheduled_date'), ['scheduled_date'], unique=False)
        batch_op.create_index(batch_op.f('ix_bookings_service_type'), ['service_type'], unique=False)
        batch_op.create_index(batch_op.f('ix_bookings_status'), ['status'], unique=False)

    op.create_table('booking_events',
    sa.Column('booking_id', sa.Uuid(), nullable=False),
    sa.Column('status', sa.String(length=32), nullable=False),
    sa.Column('note', sa.String(length=300), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('id', sa.Uuid(), nullable=False),
    sa.ForeignKeyConstraint(['booking_id'], ['bookings.id'], name=op.f('fk_booking_events_booking_id_bookings'), ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_booking_events'))
    )
    with op.batch_alter_table('booking_events', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_booking_events_booking_id'), ['booking_id'], unique=False)

    op.create_table('support_messages',
    sa.Column('customer_id', sa.Uuid(), nullable=False),
    sa.Column('booking_id', sa.Uuid(), nullable=True),
    sa.Column('sender_id', sa.Uuid(), nullable=True),
    sa.Column('from_staff', sa.Boolean(), nullable=False),
    sa.Column('body', sa.Text(), nullable=False),
    sa.Column('photo_url', sa.String(length=500), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('id', sa.Uuid(), nullable=False),
    sa.ForeignKeyConstraint(['booking_id'], ['bookings.id'], name=op.f('fk_support_messages_booking_id_bookings'), ondelete='SET NULL'),
    sa.ForeignKeyConstraint(['customer_id'], ['users.id'], name=op.f('fk_support_messages_customer_id_users'), ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['sender_id'], ['users.id'], name=op.f('fk_support_messages_sender_id_users'), ondelete='SET NULL'),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_support_messages'))
    )
    with op.batch_alter_table('support_messages', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_support_messages_booking_id'), ['booking_id'], unique=False)
        batch_op.create_index(batch_op.f('ix_support_messages_created_at'), ['created_at'], unique=False)
        batch_op.create_index(batch_op.f('ix_support_messages_customer_id'), ['customer_id'], unique=False)

    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('support_messages', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_support_messages_customer_id'))
        batch_op.drop_index(batch_op.f('ix_support_messages_created_at'))
        batch_op.drop_index(batch_op.f('ix_support_messages_booking_id'))

    op.drop_table('support_messages')
    with op.batch_alter_table('booking_events', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_booking_events_booking_id'))

    op.drop_table('booking_events')
    with op.batch_alter_table('bookings', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_bookings_status'))
        batch_op.drop_index(batch_op.f('ix_bookings_service_type'))
        batch_op.drop_index(batch_op.f('ix_bookings_scheduled_date'))
        batch_op.drop_index(batch_op.f('ix_bookings_customer_id'))

    op.drop_table('bookings')
    # ### end Alembic commands ###
